name: Test cache
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - shell: bash
        run: |
          mkdir -p /tmp/test/pkg1
          echo '1' > /tmp/test/pkg1/1

      - name: Cache test
        uses: actions/cache/save@v4
        with:
          path: |
            /tmp/test
          key: pkg1
  
      - shell: bash
        run: |
          mkdir -p /tmp/test/pkg2
          echo '2' > /tmp/test/pkg2/2

      - name: Cache test
        uses: actions/cache/save@v4
        with:
          path: |
            /tmp/test
          key: pkg2

      - shell: bash
        run: |
          rm -rf /tmp/test
          mkdir -p /tmp/test/pkg3
          echo '3' > /tmp/test/pkg3/3

      - name: Cache test
        uses: actions/cache/save@v4
        with:
          path: |
            /tmp/test
          key: pkg3

      - run: rm -rf /tmp/test
      - uses: almahmoud/multi-cache-restore-action@main
        name: Multi-cache
        with:
          keys: "'pkg1','pkg2','pkg3'"
          paths: "'/tmp/test'"

      - run: ls /tmp/test
