name: Test cache
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - shell: bash
        run: |
          mkdir -p /tmp/test/pkg1
          echo '1' > /tmp/test/pkg1/1

      - name: Cache test
        uses: actions/cache/save@v4
        with:
          path: |
            /tmp/test
          key: pkg1
  
      - shell: bash
        run: |
          mkdir -p /tmp/test/pkg2
          echo '2' > /tmp/test/pkg2/2

      - name: Cache test
        uses: actions/cache/save@v4
        with:
          path: |
            /tmp/test
          key: pkg2

      - shell: bash
        run: |
          rm -rf /tmp/test
          mkdir -p /tmp/test/pkg3
          echo '3' > /tmp/test/pkg3/3


      - name: Cache test
        uses: actions/cache/save@v4
        with:
          path: |
            /tmp/test
          key: pkg3

      - name: Install NPM package
        run: npm install @actions/cache
      - uses: actions/github-script@v7
        name: Artifact script
        with:
          script: |
            const cache = require('@actions/cache');
            const paths = [
                '/tmp/test'
            ]
            const keyList = [
                'pkg2','pkg3'
            ]

            for (const key of keyList) {
              const restoreKeys = [];
              const cacheKey = await cache.restoreCache(paths, key, restoreKeys)
            }

      - run: ls /tmp/test
